In [1]:
from CliffordAlgebras import Clifford
from pprint import pprint
import numpy as np

[NbConvertApp] Converting notebook CliffordAlgebras.ipynb to script
[NbConvertApp] Writing 14361 bytes to CliffordAlgebras.py
Populating the interactive namespace from numpy and matplotlib


In [2]:
cliff13 =Clifford(1,3)
cliff13.introduce()

My type is: (1,3)

My matrices will be 4x4, and I have K0 dimension s = 2
The generators are:
Gamma_0 = 
[[ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j -0.+0.j  0.+0.j -1.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j -0.+0.j]]
Gamma_1 = 
[[0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]]
Gamma_2 = 
[[ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [-1.+0.j -0.+0.j  0.+0.j  0.+0.j]
 [-0.+0.j -1.+0.j  0.+0.j  0.+0.j]]
Gamma_3 = 
[[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [-0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [-1.+0.j  0.+0.j -0.+0.j  0.+0.j]]


The chirality operator is:
matrix([[0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])


In [5]:
gamma0 = cliff13.generators[0]
gamma1 = cliff13.generators[1]
gamma2 = cliff13.generators[2]
gamma3 = cliff13.generators[3]
chirality13 = cliff13.chirality

In [6]:
pprint(np.dot(gamma0,gamma0)+np.dot(gamma0,gamma0)==2*np.identity(4))
pprint(np.dot(gamma1,gamma1)+np.dot(gamma1,gamma1)==-2*np.identity(4))
pprint(np.dot(gamma2,gamma2)+np.dot(gamma2,gamma2)==-2*np.identity(4))
pprint(np.dot(gamma3,gamma3)+np.dot(gamma3,gamma3)==-2*np.identity(4))
pprint(chirality13*chirality13==np.identity(4))

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [7]:
pauli = Clifford(3,0)

In [8]:
pauli.introduce()

My type is: (3,0)

My matrices will be 2x2, and I have K0 dimension s = 5
The generators are:
pauli.x = 
matrix([[0., 1.],
        [1., 0.]])
pauli.y = 
matrix([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]])
pauli.z = 
matrix([[ 1.,  0.],
        [ 0., -1.]])


The chirality operator is:
matrix([[-1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]])
